# Generated by Django 5.2.5 on 2025-08-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_flashcard',
            field=models.BooleanField(default=True, help_text='Use this question in flashcards?'),
        ),
    ]
